### PR TITLE
Show connection errors

### PR DESCRIPTION
**Pull request by matthistuff**
This will show an error message when the connection to or from a peer fails. Unfortunately it does not catch all cases as SimpleWebRTC does not expose all errors.

@alexander-heimbuch and @cmuecke please review

screen shot 2015-11-13 at 15 12 23

### CODE REVIEW

**Comment by alexander-heimbuch** [comment]
no reservations from my side, I think you have to rebase it before we can merge it.

**Comment by cmuecke** [comment]
Thumbs up, if merge conflicts are solved.

**Comment by matthistuff** [comment]
Right, will do.

**Comment by alexander-heimbuch** [comment]
whats the state of this PR?

**Comment by matthistuff** [comment]
Fighting with the rebase. Hope I'll get a chance to do this tomorrow.

**Comment by matthistuff** [comment]
Strange, this was already merged with #28. Maybe during some rebase?

**Comment by alexander-heimbuch** [comment]
:/

**Pull request closed without merging**
