### PR TITLE
streamline notification and add welcome message

### PR DESCRIPTION
**Pull request by alexander-heimbuch**

### CODE REVIEW

**Comment by alexander-heimbuch** [comment]
added welcome message and removed container status

**Comment by alexander-heimbuch** [comment]
@matthistuff please review it :)

**Comment by matthistuff** [comment]
:+1:  what does @cmuecke say about the class and id with the same name?

**Comment by alexander-heimbuch** [comment]
he doesn't like it and I think he is right :P

**Comment by matthistuff** [comment]
Then just drop it?

**Comment by alexander-heimbuch** [comment]
will add the id notificatons

**Comment by alexander-heimbuch** [comment]
ok so did a force push, should be fine now

**Pull request merged**
